version: "3.8"
services:
  database:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_USER: application
      POSTGRES_PASSWORD: 7zZpspHnpZXX5j8U
      POSTGRES_DB: application
  application:
    build:
      context: ./application
    command: /app/docker-entrypoint.sh
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: application
      DB_USER: application
      DB_PASSWORD: 7zZpspHnpZXX5j8U
    restart: always
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
  # proxy:
  #   image: nginx:1.19.1
  #   restart: always
  #   ports:
  #     - target: 80
  #       published: 8080
  #       protocol: tcp
  #       mode: host
