---
version: "3.8"
services:
  database:
    image: postgres:12.3
    restart: always
    env_file: database.env
    # ports:
    #   - target: 5432
    #     published: 5432
    #     protocol: tcp
    #     mode: host

  application:
    build:
      context: ./application
    command: /app/docker-entrypoint.sh
    restart: always
    env_file: application.env
    volumes:
      - type: volume
        source: static
        target: /app/static

  proxy:
    image: nginx:1.19.1
    restart: always
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: static
        target: /usr/share/nginx/html/static
        volume:
          nocopy: true
      - type: bind
        source: ./nginx/templates
        target: /etc/nginx/templates

volumes:
  static:
...
